apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "midas-test-1-kub"
  namespace: "default"
  labels:
    app: "midas-test-1-kub"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "midas-test-1-kub"
  template:
    metadata:
      labels:
        app: "midas-test-1-kub"
    spec:
      containers:
      - name: "quickstart-image-sha256-1"
        image: "gcr.io/midasid/quickstart-image@sha256:28aa4f036d0e29208205a329dadfebac33ea5354575eac180cc421c44a3e4d88"

apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "midas-test-1-kub-hpa-wyqk"
  namespace: "default"
  labels:
    app: "midas-test-1-kub"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "midas-test-1-kub"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80